/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSearch: typeof import('../src/components/apps/Search.vue')['default']
    ContextMenu: typeof import('./../src/components/ContextMenu.vue')['default']
    ContextMenuContainer: typeof import('./../src/components/ContextMenuContainer.vue')['default']
    DrawerSetting: typeof import('../src/components/drawerSetting/indexSetting.vue')['default']
    FormBuilder: typeof import('./../src/components/common/FormBuilder.vue')['default']
    IconSetting: typeof import('./../src/components/dialogs/iconSetting.vue')['default']
    IndexSetting: typeof import('./../src/components/drawerSetting/indexSetting.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NSlider: typeof import('naive-ui')['NSlider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/apps/Search.vue')['default']
    Wallpaper: typeof import('./../src/components/wallpaper.vue')['default']
    WallpaperSetting: typeof import('./../src/components/drawerSetting/wallpaperSetting.vue')['default']
    Widget: typeof import('./../src/components/apps/widget.vue')['default']
    WidgetSetting: typeof import('../src/components/drawerSetting/index.vue')['default']
  }
}
